# Generated by Selenium IDE (FIXED)
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


class TestTC43():

    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.wait = WebDriverWait(self.driver, 15)

        # ===== AUTO LOGIN =====
        self.driver.get("http://hauiproj.somee.com/Dangnhap.aspx")
        self.driver.set_window_size(1200, 900)

        time.sleep(1)

        self.wait.until(
            EC.presence_of_element_located(
                (By.ID, "ContentPlaceHolder1_txtTaikhoan")
            )
        ).send_keys("admin")

        time.sleep(1)

        self.driver.find_element(
            By.ID, "ContentPlaceHolder1_txtMatkhau"
        ).send_keys("1234")

        time.sleep(1)

        self.driver.find_element(
            By.ID, "ContentPlaceHolder1_btDangnhap"
        ).click()

        self.wait.until(
            EC.presence_of_element_located(
                (By.ID, "HyperLink5")
            )
        )

    def teardown_method(self, method):
        time.sleep(2)
        self.driver.quit()

    def test_tC43(self):
        self.driver.get("http://hauiproj.somee.com/Admin/Quanlydanhmuc.aspx")
        self.driver.set_window_size(986, 987)

        time.sleep(1)

        self.driver.find_element(By.CSS_SELECTOR, "#HyperLink5 > li").click()
        time.sleep(1)

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtID").send_keys("-5")
        time.sleep(1)

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTenDM").send_keys("Kính cường lực")
        time.sleep(1)

        self.driver.find_element(By.ID, "ContentPlaceHolder1_LinkButton1").click()
        time.sleep(1)

        assert "không hợp lệ" in self.driver.find_element(
            By.ID, "ContentPlaceHolder1_lblThongBao"
        ).text
