# Generated by Selenium IDE (FIXED)
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


class TestTC38():

    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.wait = WebDriverWait(self.driver, 15)

        # ======================
        # AUTO LOGIN
        # ======================
        self.driver.get("http://hauiproj.somee.com/Dangnhap.aspx")
        self.driver.set_window_size(1200, 900)

        time.sleep(1)

        # nhập tài khoản
        self.wait.until(
            EC.presence_of_element_located(
                (By.ID, "ContentPlaceHolder1_txtTaikhoan")
            )
        ).send_keys("admin")

        time.sleep(1)

        # nhập mật khẩu
        self.driver.find_element(
            By.ID, "ContentPlaceHolder1_txtMatkhau"
        ).send_keys("1234")

        time.sleep(1)

        # click đăng nhập
        self.driver.find_element(
            By.ID, "ContentPlaceHolder1_btDangnhap"
        ).click()

        # đợi menu admin xuất hiện
        self.wait.until(
            EC.presence_of_element_located(
                (By.ID, "HyperLink5")
            )
        )

    def teardown_method(self, method):
        time.sleep(2)
        self.driver.quit()

    def test_tC38(self):
        # ======================
        # TEST TC-38: Quản lý danh mục
        # ======================

        # mở trang quản lý danh mục
        self.driver.get("http://hauiproj.somee.com/Admin/Quanlydanhmuc.aspx")
        self.driver.set_window_size(1200, 900)

        time.sleep(1)

        # click menu danh mục
        self.wait.until(
            EC.element_to_be_clickable(
                (By.CSS_SELECTOR, "#HyperLink5 > li")
            )
        ).click()

        time.sleep(1)

        # nhập ID
        self.wait.until(
            EC.presence_of_element_located(
                (By.ID, "ContentPlaceHolder1_txtID")
            )
        ).click()
        self.driver.find_element(
            By.ID, "ContentPlaceHolder1_txtID"
        ).send_keys("6")

        time.sleep(1)

        # nhập tên danh mục
        self.driver.find_element(
            By.ID, "ContentPlaceHolder1_txtTenDM"
        ).click()
        self.driver.find_element(
            By.ID, "ContentPlaceHolder1_txtTenDM"
        ).send_keys("Kính cận")

        time.sleep(1)

        # click thêm / lưu
        self.driver.find_element(
            By.ID, "ContentPlaceHolder1_LinkButton1"
        ).click()

        time.sleep(2)

        # click xem danh sách
        self.driver.find_element(
            By.CSS_SELECTOR, ".khung-phai2-admin > div:nth-child(1)"
        ).click()
