# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestTC013():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()  # cần cài geckodriver
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_tC013(self):
        driver = self.driver
        wait = WebDriverWait(driver, 10)

        # 1 | Mở trang chủ
        driver.get("http://hauiproj.somee.com/Default.aspx")
        driver.set_window_size(1161, 844)
        time.sleep(1)  # chậm lại 1s

        # 2 | Click đăng nhập
        login_link = wait.until(EC.element_to_be_clickable((By.ID, "LinkDN")))
        login_link.click()
        time.sleep(1)

        # 3 | Nhập tài khoản
        username = wait.until(EC.visibility_of_element_located((By.ID, "ContentPlaceHolder1_txtTaikhoan")))
        username.click()
        username.send_keys("user")
        time.sleep(0.5)

        # 4 | Click khung để mất focus
        driver.find_element(By.CSS_SELECTOR, ".khung").click()
        time.sleep(0.5)

        # 5. Nhập mật khẩu
        password = wait.until(EC.visibility_of_element_located((By.ID, "ContentPlaceHolder1_txtMatkhau")))
        password.click()
        password.send_keys("1234")
        time.sleep(0.5)

        # 6.  Click khung để mất focus
        driver.find_element(By.CSS_SELECTOR, ".khung").click()
        time.sleep(0.5)

        # 7. Click đăng nhập
        login_btn = wait.until(EC.element_to_be_clickable((By.ID, "ContentPlaceHolder1_btDangnhap")))
        login_btn.click()
        time.sleep(1)

        # 8. Click HyperLink4
        driver.find_element(By.CSS_SELECTOR, "#HyperLink4 > li").click()
        time.sleep(1)

        # 9. Click Thanh toán
        driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
        time.sleep(1)
