# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestTC014():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()  # đảm bảo đã cài geckodriver
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_tC0s14(self):
        driver = self.driver
        wait = WebDriverWait(driver, 10)

        # 1. Mở trang chủ
        driver.get("http://hauiproj.somee.com/Default.aspx")
        driver.set_window_size(1206, 844)
        time.sleep(1)

        # 2. Click đăng nhập
        login_link = wait.until(EC.element_to_be_clickable((By.ID, "LinkDN")))
        login_link.click()
        time.sleep(1)

        # 3. Nhập tài khoản
        username = wait.until(EC.visibility_of_element_located((By.ID, "ContentPlaceHolder1_txtTaikhoan")))
        username.click()
        username.send_keys("user")
        time.sleep(0.5)
        driver.find_element(By.CSS_SELECTOR, ".khung").click()
        time.sleep(0.5)

        # 4. Nhập mật khẩu
        password = wait.until(EC.visibility_of_element_located((By.ID, "ContentPlaceHolder1_txtMatkhau")))
        password.click()
        password.send_keys("1234")
        time.sleep(0.5)
        driver.find_element(By.CSS_SELECTOR, ".khung").click()
        time.sleep(0.5)

        # 5. Click đăng nhập
        login_btn = wait.until(EC.element_to_be_clickable((By.ID, "ContentPlaceHolder1_btDangnhap")))
        login_btn.click()
        time.sleep(1)

        # 6. Click menu HyperLink2
        menu_link = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "#HyperLink2 > li")))
        menu_link.click()
        time.sleep(1)

        # 7. Chọn sản phẩm đầu tiên
        product_img = wait.until(EC.element_to_be_clickable((By.ID, "ContentPlaceHolder1_DataList1_Image1_0")))
        product_img.click()
        time.sleep(1)

        # 8. Thêm vào giỏ hàng
        add_to_cart_btn = wait.until(EC.element_to_be_clickable((By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0")))
        add_to_cart_btn.click()
        time.sleep(1)

        # 9. Click Thanh toán
        thanh_toan_btn = wait.until(EC.element_to_be_clickable((By.ID, "ContentPlaceHolder1_btnThanhToan")))
        thanh_toan_btn.click()
        time.sleep(1)

        # 10. Click ghi chú và nhập (scroll + JS click)
        ghi_chu = wait.until(EC.presence_of_element_located(
            (By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0")
        ))
        driver.execute_script("arguments[0].scrollIntoView(true);", ghi_chu)
        time.sleep(0.5)
        driver.execute_script("arguments[0].click();", ghi_chu)
        ghi_chu.send_keys("Giao hàng nhanh nha")
        time.sleep(0.5)

        # 11. Click thanh toán lần 2
        thanh_toan_user = wait.until(EC.element_to_be_clickable(
            (By.ID, "ContentPlaceHolder1_dtlThongTinUser_btnThanhToan_0")
        ))
        thanh_toan_user.click()
        time.sleep(1)

        