# Generated by Selenium IDE – FIXED
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestTC021:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()

    def teardown_method(self, method):
        self.driver.quit()

    def test_TC021_quantity_exceed_add_to_cart(self):
        driver = self.driver
        wait = WebDriverWait(driver, 15)

        # 1. Mở trang chủ
        driver.get("http://hauiproj.somee.com/Default.aspx")
        driver.set_window_size(1206, 844)
        time.sleep(1)

        # 2. Đăng nhập
        wait.until(EC.element_to_be_clickable((By.ID, "LinkDN"))).click()
        wait.until(EC.visibility_of_element_located(
            (By.ID, "ContentPlaceHolder1_txtTaikhoan"))
        ).send_keys("user")
        driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234")
        driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
        time.sleep(1)

        # 3. Vào danh sách sản phẩm
        wait.until(EC.element_to_be_clickable(
            (By.CSS_SELECTOR, "#HyperLink2 > li"))
        ).click()
        time.sleep(1)

        # 4. Chọn sản phẩm đầu tiên
        wait.until(EC.element_to_be_clickable(
            (By.ID, "ContentPlaceHolder1_DataList1_Image1_0"))
        ).click()
        time.sleep(1)

        # ===== ĐIỂM QUAN TRỌNG =====
        # 5. SET SỐ LƯỢNG = 150 TRƯỚC KHI THÊM VÀO GIỎ
        so_luong = wait.until(EC.presence_of_element_located(
            (By.XPATH, "//input[contains(@id,'SoLuong')]")
        ))

        driver.execute_script("""
            arguments[0].removeAttribute('readonly');
            arguments[0].value = '150';
            arguments[0].dispatchEvent(new Event('change'));
            arguments[0].dispatchEvent(new Event('blur'));
        """, so_luong)

        time.sleep(0.5)

        # 6. Thêm vào giỏ hàng
        wait.until(EC.element_to_be_clickable(
            (By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0"))
        ).click()
        time.sleep(1)

        # 7. Vào giỏ hàng
        wait.until(EC.element_to_be_clickable(
            (By.ID, "ContentPlaceHolder1_btnThanhToan"))
        ).click()
        time.sleep(1)

        # 8. Nhập ghi chú = abc
        ghi_chu = wait.until(EC.presence_of_element_located(
            (By.XPATH, "//textarea[contains(@id,'GhiChu')]")
        ))

        driver.execute_script("""
            arguments[0].scrollIntoView(true);
            arguments[0].value = 'abc';
            arguments[0].dispatchEvent(new Event('change'));
        """, ghi_chu)

        time.sleep(0.5)

        # 9. Ấn ĐẶT HÀNG
        wait.until(EC.element_to_be_clickable(
            (By.XPATH, "//input[contains(@id,'ThanhToan')]"))
        ).click()

        # ===== BẮT THÔNG BÁO LỖI (TRY / EXCEPT) =====
        try:
            error_elements = driver.find_elements(
                By.XPATH,
                "//*[contains(@id,'ThongBao')]"
            )

            # Không có bất kỳ thông báo nào
            if not error_elements:
                pytest.fail(
                    "BUG: KHÔNG hiển thị thông báo lỗi khi số lượng vượt quá tồn kho"
                )

            error_text = error_elements[0].text.strip()
            print("DEBUG ERROR:", repr(error_text))

            # Có element nhưng không có nội dung
            if error_text == "":
                pytest.fail(
                    "BUG: Không bắt được thông báo lỗi khi số lượng vượt quá tồn kho"
                )

        except Exception as e:
            pytest.fail(
                f"BUG: Không bắt được thông báo lỗi khi số lượng vượt quá tồn kho ({e})"
            )
