# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

DELAY = 2.5

class TestTC018:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()

    def teardown_method(self, method):
        self.driver.quit()

    def test_TC018_empty_email(self):
        driver = self.driver
        wait = WebDriverWait(driver, 10)

        # 1. Mở trang
        driver.get("http://hauiproj.somee.com/Default.aspx")
        driver.set_window_size(1206, 844)
        time.sleep(DELAY)

        # 2. Đăng nhập
        wait.until(EC.element_to_be_clickable((By.ID, "LinkDN"))).click()
        time.sleep(DELAY)

        driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("user")
        driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234")
        driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
        time.sleep(DELAY)

        # 3. Chọn sản phẩm
        wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "#HyperLink2 > li"))).click()
        time.sleep(DELAY)

        driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_0").click()
        time.sleep(DELAY)

        driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
        time.sleep(DELAY)

        driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
        time.sleep(DELAY)

        # ===== PHẦN TEST CHÍNH =====

        # 4. Điền TÊN (đúng)
        

        # 5. BỎ TRỐNG EMAIL
        email = wait.until(EC.presence_of_element_located(
            (By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtEmail_0")
        ))
        email.clear()  # cố ý để trống

       

        # 7. Ghi chú
        ghi_chu = wait.until(EC.presence_of_element_located(
            (By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0")
        ))
        ghi_chu.clear()
        ghi_chu.send_keys("abc")

        time.sleep(DELAY)

        # 8. Submit
        driver.find_element(
            By.ID, "ContentPlaceHolder1_dtlThongTinUser_btnThanhToan_0"
        ).click()

        # 9. Bắt thông báo lỗi
        error_element = WebDriverWait(driver, 10).until(
            EC.visibility_of_element_located(
                (By.ID, "ContentPlaceHolder1_dtlThongTinUser_lblThongBao_0")
            )
        )

        WebDriverWait(driver, 10).until(lambda d: error_element.text.strip() != "")
        error_text = error_element.text.strip()

        print("DEBUG ERROR TEXT:", repr(error_text))

        # 10. Assert đúng thông báo EMAIL
        assert "email" in error_text.lower(), f"Sai thông báo: {error_text}"

        time.sleep(DELAY)
