# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# Thời gian delay giữa các bước (giây)
DELAY = 2.5

class TestTC015:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()  # đảm bảo đã cài geckodriver
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_tC015(self):
        driver = self.driver
        wait = WebDriverWait(driver, 10)

        # 1. Mở trang chủ
        driver.get("http://hauiproj.somee.com/Default.aspx")
        driver.set_window_size(1206, 844)
        time.sleep(DELAY)

        # 2. Click đăng nhập
        login_link = wait.until(EC.element_to_be_clickable((By.ID, "LinkDN")))
        login_link.click()
        time.sleep(DELAY)

        # 3. Nhập tài khoản
        username = wait.until(EC.visibility_of_element_located(
            (By.ID, "ContentPlaceHolder1_txtTaikhoan")))
        username.clear()
        username.send_keys("user")
        time.sleep(DELAY)

        # 4. Nhập mật khẩu
        password = wait.until(EC.visibility_of_element_located(
            (By.ID, "ContentPlaceHolder1_txtMatkhau")))
        password.clear()
        password.send_keys("1234")
        time.sleep(DELAY)

        # 5. Click đăng nhập
        login_btn = wait.until(EC.element_to_be_clickable(
            (By.ID, "ContentPlaceHolder1_btDangnhap")))
        login_btn.click()
        time.sleep(DELAY)

        # 6. Click menu HyperLink2
        menu_link = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "#HyperLink2 > li")))
        menu_link.click()
        time.sleep(DELAY)

        # 7. Chọn sản phẩm đầu tiên
        product_img = wait.until(EC.element_to_be_clickable(
            (By.ID, "ContentPlaceHolder1_DataList1_Image1_0")))
        product_img.click()
        time.sleep(DELAY)

        # 8. Thêm vào giỏ hàng
        add_to_cart_btn = wait.until(EC.element_to_be_clickable(
            (By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0")))
        add_to_cart_btn.click()
        time.sleep(DELAY)

        # 9. Click Thanh toán
        thanh_toan_btn = wait.until(EC.element_to_be_clickable(
            (By.ID, "ContentPlaceHolder1_btnThanhToan")))
        thanh_toan_btn.click()
        time.sleep(DELAY)

        # 10. Bỏ trống ghi chú
        ghi_chu = wait.until(EC.presence_of_element_located(
            (By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0")))
        ghi_chu.clear()
        ghi_chu.send_keys("")  # đảm bảo trống
        time.sleep(DELAY)

        # 11. Click thanh toán lần 2
        thanh_toan_user = wait.until(EC.element_to_be_clickable(
            (By.ID, "ContentPlaceHolder1_dtlThongTinUser_btnThanhToan_0")))
        thanh_toan_user.click()

        # 12. Lấy thông báo lỗi
        # Lấy element mới sau click, tránh dùng reference cũ
        error_element = WebDriverWait(driver, 10).until(
            EC.visibility_of_element_located(
                (By.ID, "ContentPlaceHolder1_dtlThongTinUser_lblThongBao_0")
            )
        )

        # Chờ text không rỗng (tránh lấy quá sớm)
        WebDriverWait(driver, 10).until(lambda d: error_element.text.strip() != "")
        error_text = error_element.text.strip()

        # In debug
        print(f"DEBUG: error_text = {repr(error_text)}")

        # 13. Assert thông báo lỗi (dùng in để tránh fail do ký tự thừa)
        assert "Nhập ghi chú" in error_text, f"Expected 'Nhập ghi chú', but got '{error_text}'"

        # 14. Dừng cuối cùng để quan sát
        time.sleep(DELAY)
