# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

DELAY = 2.5

class TestTC020:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()

    def teardown_method(self, method):
        self.driver.quit()

    def test_TC020_empty_email_and_address(self):
        driver = self.driver
        wait = WebDriverWait(driver, 15)

        # 1. Mở trang
        driver.get("http://hauiproj.somee.com/Default.aspx")
        driver.set_window_size(1206, 844)
        time.sleep(DELAY)

        # 2. Đăng nhập
        wait.until(EC.element_to_be_clickable((By.ID, "LinkDN"))).click()
        time.sleep(DELAY)

        driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("user")
        driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234")
        driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
        time.sleep(DELAY)

        # 3. Chọn sản phẩm
        wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "#HyperLink2 > li"))).click()
        time.sleep(DELAY)

        driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_0").click()
        time.sleep(DELAY)

        driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
        time.sleep(DELAY)

        driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
        time.sleep(DELAY)

        # ===== PHẦN TEST CHÍNH =====

        # BỎ TRỐNG EMAIL
        email_list = driver.find_elements(
            By.XPATH,
            "//input[contains(@id,'Email')]"
        )
        assert len(email_list) > 0, "Không tìm thấy trường Email"
        driver.execute_script("arguments[0].value='';", email_list[0])

        # BỎ TRỐNG ĐỊA CHỈ
        dia_chi_list = driver.find_elements(
            By.XPATH,
            "//input[contains(@id,'DiaChi')] | //textarea[contains(@id,'DiaChi')]"
        )
        assert len(dia_chi_list) > 0, "Không tìm thấy trường Địa chỉ"
        driver.execute_script("arguments[0].value='';", dia_chi_list[0])

        #  GHI CHÚ = "abc"
        ghi_chu = wait.until(
            EC.presence_of_element_located(
                (By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0")
            )
        )
        ghi_chu.clear()
        ghi_chu.send_keys("abc")

        time.sleep(DELAY)

        #  SUBMIT
        driver.find_element(
            By.ID, "ContentPlaceHolder1_dtlThongTinUser_btnThanhToan_0"
        ).click()

        # ===== BẮT THÔNG BÁO LỖI (NEGATIVE TEST – ĐÚNG NGHIỆP VỤ) =====
        time.sleep(1.5)  # chờ ASP.NET postback render thông báo

        try:
            error_elements = driver.find_elements(
                By.XPATH,
                "//*[contains(@id,'ThongBao') and normalize-space(text())!='']"
            )

            # Không có thông báo lỗi nào
            if not error_elements:
                pytest.fail(
                    "BUG: Bỏ trống Email và Địa chỉ nhưng hệ thống KHÔNG hiển thị thông báo lỗi"
                )

            error_texts = [e.text.strip() for e in error_elements]
            print("DEBUG ERROR TEXTS:", error_texts)

            has_email_error = any("email" in t.lower() for t in error_texts)
            has_address_error = any(
                "địa chỉ" in t.lower() or "dia chi" in t.lower()
                for t in error_texts
            )

            # Thiếu 1 trong 2 thông báo
            if not has_email_error or not has_address_error:
                pytest.fail(
                    "BUG: Bỏ trống Email và Địa chỉ nhưng hệ thống CHỈ hiển thị "
                    f"{len(error_texts)} thông báo: {error_texts}"
                )

        except Exception as e:
            pytest.fail(f"Lỗi khi kiểm tra thông báo validate: {e}")

        time.sleep(DELAY)
