# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestTC03():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.wait = WebDriverWait(self.driver, 10)

    def teardown_method(self, method):
        self.driver.quit()

    def slow(self, seconds=1):
        time.sleep(seconds)

    def test_tC03(self):
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.slow(1)

        self.driver.set_window_size(1550, 926)
        self.slow(1)

        self.driver.find_element(By.ID, "LinkDN").click()
        self.slow(1)

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("abc")
        self.slow(1)

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("12345")
        self.slow(1)

        self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
        self.slow(2)

        msg = self.wait.until(
            EC.visibility_of_element_located(
                (By.ID, "ContentPlaceHolder1_txtThongbaoDN")
            )
        )
        self.slow(1)

        assert msg.text == "Sai tên tài khoản hoặc mật khẩu!"
