# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC07():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  def slow(self, seconds=1):
        time.sleep(seconds)
  
  def test_tC07(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.slow(1)
    self.driver.set_window_size(1550, 926)
    self.slow(1)
    self.driver.find_element(By.ID, "LinkDN").click()
    self.slow(1)
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    self.slow(2)
    assert self.driver.find_element(By.ID, "ContentPlaceHolder1_txtThongbaoDN").text == "Vui lòng nhập tài khoản và mật khẩu!"
    
  
