# Generated by Selenium IDE – FIXED SINGLE TAB VERSION

import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException

URL = "http://hauiproj.somee.com/Default.aspx"


# ========= DRIVER DÙNG CHUNG =========
@pytest.fixture(scope="session")
def driver():
    driver = webdriver.Firefox()
    driver.set_window_size(1550, 926)
    yield driver
    time.sleep(2)
    driver.quit()


def slow(sec=1):
    time.sleep(sec)


def open_home(driver):
    driver.get(URL)
    slow(1)


def logout_if_logged_in(driver):
    try:
        driver.find_element(By.ID, "LinkDX").click()
        slow(1)
    except:
        pass


# ========= TC01 =========
def test_TC01_user_login_logout(driver):
    open_home(driver)
    driver.find_element(By.ID, "LinkDN").click()
    slow()

    driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("abc")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("abc")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    slow(2)

    logout_if_logged_in(driver)


# ========= TC02 =========
def test_TC02_admin_login_logout(driver):
    open_home(driver)
    driver.find_element(By.ID, "LinkDN").click()
    slow()

    driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("admin")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    slow(2)

    logout_if_logged_in(driver)


# ========= TC03 =========
def test_TC03_wrong_password(driver):
    open_home(driver)
    driver.find_element(By.ID, "LinkDN").click()
    slow()

    driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("abc")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("12345")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    slow(2)

    msg = WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.ID, "ContentPlaceHolder1_txtThongbaoDN"))
    )
    assert msg.text == "Sai tên tài khoản hoặc mật khẩu!"


# ========= TC04 =========
def test_TC04_wrong_username(driver):
    open_home(driver)
    driver.find_element(By.ID, "LinkDN").click()
    slow()

    driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("abe")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("abc")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    slow(2)

    msg = WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.ID, "ContentPlaceHolder1_txtThongbaoDN"))
    )
    assert msg.text == "Sai tên tài khoản hoặc mật khẩu!"


# ========= TC05 =========
def test_TC05_missing_username(driver):
    open_home(driver)
    driver.find_element(By.ID, "LinkDN").click()
    slow()

    driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("12345")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    slow(2)

    msg = WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.ID, "ContentPlaceHolder1_txtThongbaoDN"))
    )
    assert msg.text == "Vui lòng nhập tài khoản và mật khẩu!"


# ========= TC06 =========
def test_TC06_missing_password(driver):
    open_home(driver)
    driver.find_element(By.ID, "LinkDN").click()
    slow()

    driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("abc")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    slow(2)

    msg = WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.ID, "ContentPlaceHolder1_txtThongbaoDN"))
    )
    assert msg.text == "Vui lòng nhập tài khoản và mật khẩu!"


# ========= TC07 =========
def test_TC07_empty_login(driver):
    open_home(driver)
    driver.find_element(By.ID, "LinkDN").click()
    slow()

    driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    slow(2)
    msg = driver.find_element(By.ID, "ContentPlaceHolder1_txtThongbaoDN")
    assert msg.text == "Vui lòng nhập tài khoản và mật khẩu!"


# ========= TC08 =========
def test_TC08_random_account(driver):
    open_home(driver)
    driver.find_element(By.ID, "LinkDN").click()
    slow()

    driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("aaaae")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("aaaae")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    slow(2)

    msg = WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.ID, "ContentPlaceHolder1_txtThongbaoDN"))
    )
    assert msg.text == "Sai tên tài khoản hoặc mật khẩu!"


# ========= TC09 =========
def test_TC09_back_button(driver):
    open_home(driver)
    driver.find_element(By.ID, "LinkDN").click()
    slow()

    driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("abc")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("123")
    slow(1)
    driver.find_element(By.LINK_TEXT, "Quay lại").click()
    slow(4)

    driver.find_element(By.ID, "LinkDN").click()
    slow(2)


# ========= TC10 – MỞ TAB THỨ 2 =========
def test_TC10_two_tabs_same_session(driver):
    wait = WebDriverWait(driver, 5)

    # TAB 1
    open_home(driver)
    driver.find_element(By.ID, "LinkDN").click()
    slow()

    # TAB 2
    driver.execute_script("window.open('');")
    driver.switch_to.window(driver.window_handles[1])
    open_home(driver)
    driver.find_element(By.ID, "LinkDN").click()
    slow()

    # TAB 1 login
    driver.switch_to.window(driver.window_handles[0])
    driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("abc")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("abc")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    slow(2)

    # TAB 2 login
    driver.switch_to.window(driver.window_handles[1])
    driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("admin")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234")
    slow(1)
    driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()

    try:
        wait.until(
            EC.visibility_of_element_located((By.ID, "ContentPlaceHolder1_txtThongbaoDN"))
        )
        assert True
    except TimeoutException:
        pytest.fail(
            "BUG: Dùng chung session giữa các tab, không tách phiên"
        )
