# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestTC06():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.wait = WebDriverWait(self.driver, 10)

    def teardown_method(self, method):
        self.driver.quit()

    def slow(self, seconds=1):
        time.sleep(seconds)

    def test_tC06(self):
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.slow(2)

        self.driver.set_window_size(1550, 926)
        self.slow(1)

        # Mở form đăng nhập
        self.wait.until(
            EC.element_to_be_clickable((By.ID, "LinkDN"))
        ).click()
        self.slow(1)

        # Chỉ nhập tài khoản (thiếu mật khẩu)
        self.wait.until(
            EC.visibility_of_element_located(
                (By.ID, "ContentPlaceHolder1_txtTaikhoan")
            )
        ).send_keys("abc")
        self.slow(1)

        # Click đăng nhập
        self.wait.until(
            EC.element_to_be_clickable(
                (By.ID, "ContentPlaceHolder1_btDangnhap")
            )
        ).click()
        self.slow(2)

        # Kiểm tra thông báo lỗi
        msg = self.wait.until(
            EC.visibility_of_element_located(
                (By.ID, "ContentPlaceHolder1_txtThongbaoDN")
            )
        )
        self.slow(2)

        assert msg.text == "Vui lòng nhập tài khoản và mật khẩu!"
