# Generated by Selenium IDE - Fixed for PyCharm
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTC027():
    def setup_method(self, method):
        # Chuyển sang Chrome để chạy ổn định trên môi trường Windows của bạn
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)  # Chờ ngầm định tối đa 10 giây
        self.vars = {}

    def teardown_method(self, method):
        # Dừng 3 giây để bạn kịp quan sát thông báo lỗi trước khi đóng trình duyệt
        time.sleep(3)
        self.driver.quit()

    def test_tC027(self):
        # 1. Truy cập trang web và tối ưu hóa hiển thị
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.driver.maximize_window()

        # 2. Click vào liên kết Đăng ký
        self.driver.find_element(By.ID, "LinkDK").click()

        # 3. Nhập dữ liệu (Lược bỏ các bước click thừa để code chạy nhanh hơn)
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaiKhoan").send_keys("HaiYen123412")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatKhau").send_keys("Yen@12345")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtHoTen").send_keys("Nguyễn Thị hải Yến")

        # Lưu ý: TC_027 bỏ trống Năm Sinh

        # Chọn giới tính Nữ
        dropdown = self.driver.find_element(By.ID, "ContentPlaceHolder1_dllGioiTinh")
        dropdown.find_element(By.XPATH, "//option[. = 'Nữ']").click()

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtEmail").send_keys("nguyen@gmail.com")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtSdt").send_keys("0982736222")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtDiaChi").send_keys("Bắc giang")

        # 4. Click nút Đăng ký bằng JavaScript để tránh lỗi bị che khuất (Intercepted)
        btn_dangky = self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangky")
        self.driver.execute_script("arguments[0].scrollIntoView();", btn_dangky)  # Cuộn tới nút
        time.sleep(1)  # Chờ 1 giây cho trang ổn định
        self.driver.execute_script("arguments[0].click();", btn_dangky)  # Click cưỡng bách

        # 5. Kiểm tra thông báo lỗi (Assert text)
        # Lấy nội dung thông báo từ thẻ lblThongBao
        thong_bao = self.driver.find_element(By.ID, "ContentPlaceHolder1_lblThongBao").text

        # Hiển thị thông báo ra bảng Run để bạn dễ kiểm tra
        print(f"\nThông báo nhận được: {thong_bao}")

        # Assert: Kiểm tra xem thông báo có chứa nội dung yêu cầu nhập ngày sinh không
        assert "Nhập ngày sinh" in thong_bao or thong_bao != ""