# Generated by Selenium IDE - Fixed for PyCharm
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTC031():
    def setup_method(self, method):
        # Sử dụng Chrome để chạy ổn định và tránh lỗi driver Firefox
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)  # Chờ ngầm định tối đa 10s để tìm phần tử
        self.vars = {}

    def teardown_method(self, method):
        # Dừng 3 giây để quan sát kết quả trước khi đóng trình duyệt
        time.sleep(3)
        self.driver.quit()

    def test_tC031(self):
        # 1. Truy cập trang web và phóng to cửa sổ
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.driver.maximize_window()

        # 2. Click vào liên kết Đăng ký
        self.driver.find_element(By.ID, "LinkDK").click()

        # 3. Nhập dữ liệu (Lược bỏ các thao tác .click() trung gian để code gọn hơn)
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaiKhoan").send_keys("HaiYen123412")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatKhau").send_keys("Yen@12345")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtHoTen").send_keys("Nguyễn Thị Hải Yến")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtNamSinh").send_keys("2025-12-15")

        # Chọn giới tính Nữ
        dropdown = self.driver.find_element(By.ID, "ContentPlaceHolder1_dllGioiTinh")
        dropdown.find_element(By.XPATH, "//option[. = 'Nữ']").click()

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtEmail").send_keys("nguyen@gmail.com")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtSdt").send_keys("0982736222")

        # Lưu ý: TC_031 bỏ trống trường Địa chỉ (txtDiaChi)

        # 4. Click nút Đăng ký bằng JavaScript để tránh lỗi ElementClickIntercepted
        btn_dangky = self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangky")
        self.driver.execute_script("arguments[0].scrollIntoView();", btn_dangky)
        time.sleep(1)  # Chờ 1s để trang ổn định
        self.driver.execute_script("arguments[0].click();", btn_dangky)

        # 5. PHẦN ASSERT TEXT: Kiểm tra thông báo lỗi
        # Sử dụng .strip() để loại bỏ các khoảng trắng thừa nếu có
        thong_bao_thuc_te = self.driver.find_element(By.ID, "ContentPlaceHolder1_lblThongBao").text.strip()

        print(f"\nThông báo nhận được: '{thong_bao_thuc_te}'")

        # Kiểm tra nội dung thông báo
        assert thong_bao_thuc_te == "Nhập địa chỉ"