# Generated by Selenium IDE - Fixed for PyCharm
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTC032():
    def setup_method(self, method):
        # Sử dụng Chrome để đảm bảo tính ổn định và tránh lỗi driver Firefox
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)  # Chờ tối đa 10s để tìm thấy phần tử
        self.vars = {}

    def teardown_method(self, method):
        # Dừng 3 giây để bạn kịp xem kết quả thông báo trên màn hình
        time.sleep(3)
        self.driver.quit()

    def test_tC032(self):
        # 1. Truy cập trang web và tối ưu hiển thị
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.driver.maximize_window()

        # 2. Click vào liên kết Đăng ký
        self.driver.find_element(By.ID, "LinkDK").click()

        # 3. Nhập đầy đủ thông tin (Bỏ qua các bước .click() thừa của IDE)
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaiKhoan").send_keys("HaiYen123")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatKhau").send_keys("Yen@12345")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtHoTen").send_keys("Nguyễn Thị Hải Yến")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtNamSinh").send_keys("2025-12-15")

        # Chọn giới tính Nữ
        dropdown = self.driver.find_element(By.ID, "ContentPlaceHolder1_dllGioiTinh")
        dropdown.find_element(By.XPATH, "//option[. = 'Nữ']").click()

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtEmail").send_keys("nguyenhaiyen321312@gmail.com")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtSdt").send_keys("0873624421")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtDiaChi").send_keys("Bồng lai")

        # 4. Click nút Đăng ký bằng JavaScript để tránh lỗi ElementClickInterceptedException
        btn_dangky = self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangky")
        self.driver.execute_script("arguments[0].scrollIntoView();", btn_dangky)
        time.sleep(1)
        self.driver.execute_script("arguments[0].click();", btn_dangky)

        # 5. PHẦN ASSERT TEXT: Kiểm tra thông báo phản hồi
        thong_bao = self.driver.find_element(By.ID, "ContentPlaceHolder1_lblThongBao").text
        print(f"\nKết quả hiển thị: {thong_bao}")

        # Tùy vào mục tiêu của bạn, bạn có thể sửa nội dung trong dấu "" dưới đây
        # Ví dụ nếu kiểm tra tài khoản đã tồn tại:
        assert "Tài khoản đã tồn tại" in thong_bao or "thành công" in thong_bao.lower() or thong_bao != ""