# Generated by Selenium IDE - Fixed for PyCharm
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTC035():
    def setup_method(self, method):
        # Chuyển sang Chrome để đảm bảo chạy ổn định trên PyCharm 2025
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)  # Chờ tối đa 10 giây để tìm thấy phần tử
        self.vars = {}

    def teardown_method(self, method):
        # Dừng 3 giây để bạn kịp quan sát kết quả Assert trước khi đóng trình duyệt
        time.sleep(3)
        self.driver.quit()

    def test_tC035(self):
        # 1. Truy cập trang web và tối ưu hiển thị
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.driver.maximize_window()

        # 2. Vào trang Đăng ký
        self.driver.find_element(By.ID, "LinkDK").click()

        # 3. Nhập dữ liệu (Lược bỏ các lệnh click thừa để tối ưu tốc độ)
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaiKhoan").send_keys("HaiYen131212")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatKhau").send_keys("Yen@12345")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtHoTen").send_keys("Nguyễn Thị Hải Yến@#")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtNamSinh").send_keys("2025-12-15")

        # Chọn giới tính Nữ
        dropdown = self.driver.find_element(By.ID, "ContentPlaceHolder1_dllGioiTinh")
        dropdown.find_element(By.XPATH, "//option[. = 'Nữ']").click()

        # Nhập Email sai định dạng để test lỗi
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtEmail").send_keys("nguyenhaiyen321312com")

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtSdt").send_keys("0873624421#@")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtDiaChi").send_keys("Bồng lai")

        # 4. Click nút Đăng ký bằng JavaScript để tránh lỗi bị che khuất phần tử
        btn_dangky = self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangky")
        self.driver.execute_script("arguments[0].scrollIntoView();", btn_dangky)
        time.sleep(1)
        self.driver.execute_script("arguments[0].click();", btn_dangky)

        # 5. PHẦN ASSERT TEXT: Kiểm tra thông báo lỗi
        # Lấy nội dung thông báo và loại bỏ khoảng trắng thừa
        thong_bao_thuc_te = self.driver.find_element(By.ID, "ContentPlaceHolder1_lblThongBao").text.strip()

        print(f"\nThông báo nhận được: '{thong_bao_thuc_te}'")

        # Xác nhận hệ thống báo đúng lỗi "Email không hợp lệ"
        assert thong_bao_thuc_te == "Email không hợp lệ"