# Generated by Selenium IDE - Fixed for PyCharm
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTC037():
    def setup_method(self, method):
        # Sử dụng Chrome để đảm bảo chạy ổn định trên PyCharm 2025
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)  # Chờ tối đa 10 giây để tìm thấy phần tử
        self.vars = {}

    def teardown_method(self, method):
        # Dừng 3 giây để bạn kịp quan sát kết quả Assert trước khi đóng trình duyệt
        time.sleep(3)
        self.driver.quit()

    def test_tC037(self):
        # 1. Truy cập trang web và phóng to cửa sổ
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.driver.maximize_window()

        # 2. Vào trang Đăng ký
        self.driver.find_element(By.ID, "LinkDK").click()

        # 3. Nhập dữ liệu (Lược bỏ các lệnh click thừa để tối ưu tốc độ)
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaiKhoan").send_keys("HaiYen32")

        # Nhập mật khẩu (Giả sử test case này kiểm tra mật khẩu yếu hoặc ngắn)
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatKhau").send_keys("wefwef")

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtHoTen").send_keys("Nguyễn Hai yen")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtNamSinh").send_keys("2025-12-01")

        # Giới tính mặc định hoặc chọn Nữ (Nếu cần)
        # self.driver.find_element(By.ID, "ContentPlaceHolder1_dllGioiTinh").click()

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtEmail").send_keys("âcsfasd@gmail.com")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtSdt").send_keys("086726234")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtDiaChi").send_keys("Bắc ninh")

        # 4. Click nút Đăng ký bằng JavaScript để tránh lỗi ElementClickInterceptedException
        btn_dangky = self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangky")
        self.driver.execute_script("arguments[0].scrollIntoView();", btn_dangky)
        time.sleep(1)
        self.driver.execute_script("arguments[0].click();", btn_dangky)

        # 5. PHẦN ASSERT TEXT: Kiểm tra thông báo lỗi
        # Lấy nội dung thông báo lỗi thực tế trên trang web
        thong_bao_thuc_te = self.driver.find_element(By.ID, "ContentPlaceHolder1_lblThongBao").text.strip()

        print(f"\nThông báo nhận được: '{thong_bao_thuc_te}'")

        # Kiểm tra xem thông báo có xuất hiện hay không (Bạn có thể sửa nội dung trong dấu "" cho khớp với yêu cầu)
        assert thong_bao_thuc_te != ""
        # Nếu bạn muốn check cụ thể, hãy dùng: assert thong_bao_thuc_te == "Mật khẩu quá ngắn" (ví dụ)