# Generated by Selenium IDE - Fixed for PyCharm
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTC028():
    def setup_method(self, method):
        # Chuyển sang Chrome để chạy ổn định
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)
        self.vars = {}

    def teardown_method(self, method):
        time.sleep(3)
        self.driver.quit()

    def test_tC028(self):
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.driver.maximize_window()

        # 1. Click vào liên kết Đăng ký
        self.driver.find_element(By.ID, "LinkDK").click()

        # 2. Click trực tiếp vào nút Đăng ký khi chưa nhập gì
        btn_dangky = self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangky")
        self.driver.execute_script("arguments[0].click();", btn_dangky)

        # 3. PHẦN ASSERT TEXT ĐÂY BẠN NHÉ:
        # Lấy văn bản từ phần tử hiển thị thông báo lỗi
        thong_bao_thuc_te = self.driver.find_element(By.ID, "ContentPlaceHolder1_lblThongBao").text

        # In ra để bạn nhìn thấy trong tab Run
        print(f"\nThông báo lỗi xuất hiện là: {thong_bao_thuc_te}")

        # Dòng lệnh Assert: So sánh nội dung thực tế với mong đợi
        # Nếu thong_bao_thuc_te không phải là "Nhập tài khoản", PyCharm sẽ báo đỏ lỗi ngay.
        assert thong_bao_thuc_te == "Nhập tài khoản"