# Generated by Selenium IDE - Fixed for PyCharm
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTC030():
    def setup_method(self, method):
        # Sử dụng Chrome để đồng bộ với các bài trước và đảm bảo tính ổn định
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)  # Chờ ngầm định tối đa 10s để tìm phần tử
        self.vars = {}

    def teardown_method(self, method):
        # Dừng 3 giây để bạn kịp quan sát thông báo lỗi trước khi đóng trình duyệt
        time.sleep(3)
        self.driver.quit()

    def test_tC030(self):
        # 1. Truy cập trang web và phóng to cửa sổ
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.driver.maximize_window()

        # 2. Click vào liên kết Đăng ký
        self.driver.find_element(By.ID, "LinkDK").click()

        # 3. Nhập dữ liệu (Lược bỏ các bước click thừa để code chạy mượt hơn)
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaiKhoan").send_keys("HaiYen123412")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatKhau").send_keys("Yen@12345")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtHoTen").send_keys("Nguyễn Thị Hải Yến")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtNamSinh").send_keys("2025-12-15")

        # Chọn giới tính Nữ
        dropdown = self.driver.find_element(By.ID, "ContentPlaceHolder1_dllGioiTinh")
        dropdown.find_element(By.XPATH, "//option[. = 'Nữ']").click()

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtEmail").send_keys("nguyen@gmail.com")

        # Lưu ý: TC_030 bỏ trống trường Số điện thoại (txtSdt)

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtDiaChi").send_keys("Bắc giang")

        # 4. Click nút Đăng ký bằng JavaScript để tránh lỗi bị che khuất (Intercepted)
        btn_dangky = self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangky")
        self.driver.execute_script("arguments[0].scrollIntoView();", btn_dangky)  # Cuộn tới nút
        time.sleep(1)  # Chờ 1 giây cho trang ổn định
        self.driver.execute_script("arguments[0].click();", btn_dangky)  # Click cưỡng bách

        # 5. PHẦN ASSERT TEXT: Kiểm tra thông báo lỗi có khớp chính xác không
        thong_bao_thuc_te = self.driver.find_element(By.ID, "ContentPlaceHolder1_lblThongBao").text

        # In kết quả ra bảng Run của PyCharm để bạn dễ theo dõi
        print(f"\nThông báo nhận được: {thong_bao_thuc_te}")

        # Kiểm tra xem thông báo có đúng là "Nhập số điện thoại" không
        assert thong_bao_thuc_te == "Nhập số điện thoại"