# Generated by Selenium IDE - Fixed for PyCharm
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTC033():
    def setup_method(self, method):
        # Sử dụng Chrome để đảm bảo chạy ổn định trên PyCharm của bạn
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)  # Chờ tối đa 10 giây để tìm thấy các phần tử
        self.vars = {}

    def teardown_method(self, method):
        # Tạm dừng 3 giây để bạn xem kết quả Assert trước khi đóng trình duyệt
        time.sleep(3)
        self.driver.quit()

    def test_tC033(self):
        # 1. Truy cập trang web và phóng to cửa sổ
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.driver.maximize_window()

        # 2. Đi tới trang Đăng ký
        self.driver.find_element(By.ID, "LinkDK").click()

        # 3. Nhập dữ liệu (Lược bỏ các lệnh click thừa để tối ưu tốc độ)
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaiKhoan").send_keys("HaiYen12132")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatKhau").send_keys("Yen@12345")

        # Nhập họ tên chứa ký tự đặc biệt để test lỗi
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtHoTen").send_keys("Nguyễn Thị Hải Yến@#")

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtNamSinh").send_keys("2025-12-15")

        # Chọn giới tính Nữ
        dropdown = self.driver.find_element(By.ID, "ContentPlaceHolder1_dllGioiTinh")
        dropdown.find_element(By.XPATH, "//option[. = 'Nữ']").click()

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtEmail").send_keys("nguyenhaiyen321312@gmail.com")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtSdt").send_keys("0873624421")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtDiaChi").send_keys("Bồng lai")

        # 4. Click nút Đăng ký bằng JavaScript để tránh lỗi bị che khuất phần tử
        btn_dangky = self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangky")
        self.driver.execute_script("arguments[0].scrollIntoView();", btn_dangky)
        time.sleep(1)  # Chờ 1 giây để đảm bảo trang đã sẵn sàng
        self.driver.execute_script("arguments[0].click();", btn_dangky)

        # 5. PHẦN ASSERT TEXT: Kiểm tra thông báo lỗi
        thong_bao_thuc_te = self.driver.find_element(By.ID, "ContentPlaceHolder1_lblThongBao").text.strip()

        # In kết quả ra màn hình Run để đối chiếu
        print(f"\nThông báo nhận được: '{thong_bao_thuc_te}'")

        # So sánh với mong đợi
        assert thong_bao_thuc_te == "Họ tên không được chứa số hoặc kí tự đặc biệt"